name: bk-tutorial
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - pip
  - geojson
  - geopandas
  - jupyter_client<8
  - notebook
  - pandas
  - pyshp
  - ipykernel
  - pip:
      - bokeh==3.5
      - bokeh_sampledata
